# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

store1 = Store.create(name: 'Fridge', description: 'Wine Refridgerator')
store1.locations.create(position: 'r1_c1_f', description: 'Row 1, Col 1, Front') 
store1.locations.create(position: 'r1_c2_f', description: 'Row 1, Col 2, Front') 
store1.locations.create(position: 'r1_c3_f', description: 'Row 1, Col 3, Front') 
store1.locations.create(position: 'r1_c4_f', description: 'Row 1, Col 4, Front') 
store1.locations.create(position: 'r1_c1_b', description: 'Row 1, Col 1, Back') 
store1.locations.create(position: 'r1_c2_b', description: 'Row 1, Col 2, Back') 
store1.locations.create(position: 'r1_c3_b', description: 'Row 1, Col 3, Back') 
store1.locations.create(position: 'r1_c4_b', description: 'Row 1, Col 4, Back') 
store1.locations.create(position: 'r2_c1_f', description: 'Row 2, Col 1, Front') 
store1.locations.create(position: 'r2_c2_f', description: 'Row 2, Col 2, Front') 
store1.locations.create(position: 'r2_c3_f', description: 'Row 2, Col 3, Front') 
store1.locations.create(position: 'r2_c4_f', description: 'Row 2, Col 4, Front') 
store1.locations.create(position: 'r2_c1_b', description: 'Row 2, Col 1, Back') 
store1.locations.create(position: 'r2_c2_b', description: 'Row 2, Col 2, Back') 
store1.locations.create(position: 'r2_c3_b', description: 'Row 2, Col 3, Back') 
store1.locations.create(position: 'r2_c4_b', description: 'Row 2, Col 4, Back') 

store2 = Store.create(name: 'Rack', description: 'Wine Rack')
store2.locations.create(position: 'r1_c1', description: 'Row 1, Col 1') 
store2.locations.create(position: 'r1_c2', description: 'Row 1, Col 2') 
store2.locations.create(position: 'r1_c2', description: 'Row 1, Col 3') 
store2.locations.create(position: 'r2_c1', description: 'Row 2, Col 1') 
store2.locations.create(position: 'r2_c2', description: 'Row 2, Col 2') 
store2.locations.create(position: 'r2_c2', description: 'Row 2, Col 3') 
store2.locations.create(position: 'r3_c1', description: 'Row 3, Col 1') 
store2.locations.create(position: 'r3_c2', description: 'Row 3, Col 2') 
store2.locations.create(position: 'r3_c2', description: 'Row 3, Col 3') 

Wine.create(name: 'Dulcet', vineyard: 'BV', region: 'Rutherford', category: 'Cabernet', year: 2003, price: 55, note: '', size: 750, location_id:1)
Wine.create(name: 'Rubicon', vineyard: 'Inglenook', region: 'Rutherford', category: 'Cabernet', year: 2012, price: 210, note: '', size: 750, location_id:2)
Wine.create(name: 'Marinus', vineyard: 'Bernardus', region: 'Carmel Valley', category: 'Cabernet', year: 2004, price: 25, note: '', size: 375, location_id:3)
Wine.create(name: 'George de Latour', vineyard: 'BV', region: 'Rutherford', category: 'Cabernet', year: 2012, price: 135, note: '', size: 750, location_id:4)
Wine.create(name: 'Stags SLV', vineyard: 'Stags Leap Cellars', region: 'Stags Leap District', category: 'Cabernet', year: 2008, price: 125, note: '', size: 750, location_id:5)
Wine.create(name: 'Opus One', vineyard: 'Opus One Winery', region: 'Oakville', category: 'Cabernet', year: 2009, price: 360, note: '', size: 750, location_id:6)
Wine.create(name: 'Opus One', vineyard: 'Opus One Winery', region: 'Oakville', category: 'Cabernet', year: 2011, price: 230, note: '', size: 750, location_id:7)
Wine.create(name: 'Clone 6', vineyard: 'BV', region: 'Rutherford', category: 'Cabernet', year: 2006, price: 180, note: '', size: 750, location_id:8)
Wine.create(name: 'Clone 4', vineyard: 'BV', region: 'Rutherford', category: 'Cabernet', year: 2011, price: 140, note: '', size: 750, location_id:9)
Wine.create(name: 'Goldeneye', vineyard: 'Goldeneye', region: 'Anderson Valley', category: 'Pinot Noir', year: 2012, price: 80, note: 'Red-cherry and strawberry aromas', size: 750, location_id:10)
Wine.create(name: 'Silver Oak', vineyard: 'Silver Oak Cellars', region: 'Alexander Valley', category: 'Cabernet', year: 2004, price: 100, note: '', size: 750, location_id:11)
Wine.create(name: 'Silver Oak', vineyard: 'Silver Oak Cellars', region: 'Napa Valley', category: 'Cabernet', year: 2010, price: 110, note: '', size: 750, location_id:12)
Wine.create(name: 'Elu', vineyard: 'St. Supery', region: 'Rutherford', category: 'Red Blend', year: 2012, price: 75, note: '', size: 750, location_id:13)
Wine.create(name: 'Oakville East', vineyard: 'Oakville East', region: 'Oakville', category: 'Cabernet', year: 2009, price: 100, note: '', size: 750, location_id:14)
Wine.create(name: 'Isoceles', vineyard: 'Justin', region: 'Paso Robles', category: 'Cabernet', year: 2009, price: 70, note: '', size: 750, location_id:15)
Wine.create(name: 'Isoceles', vineyard: 'Justin', region: 'Paso Robles', category: 'Cabernet', year: 2010, price: 70, note: '', size: 750, location_id:16)
Wine.create(name: 'Isoceles', vineyard: 'Justin', region: 'Paso Robles', category: 'Cabernet', year: 2011, price: 70, note: '', size: 750, location_id:17)
Wine.create(name: 'Tapestry', vineyard: 'BV', region: 'Rutherford', category: 'Cabernet', year: 2012, price: 65, note: '', size: 750, location_id:18)
Wine.create(name: 'Tapestry', vineyard: 'BV', region: 'Rutherford', category: 'Cabernet', year: 2013, price: 65, note: '', size: 750, location_id:19)
Wine.create(name: 'Mastery', vineyard: 'Mastery', region: 'Yountville', category: 'Cabernet', year: 2013, price: 95, note: '', size: 750, location_id:20)
Wine.create(name: 'Maestro', vineyard: 'BV', region: 'Rutherford', category: 'Red Blend', year: 2011, price: 75, note: '', size: 750, location_id:21)
Wine.create(name: 'BV Pinot', vineyard: 'BV', region: 'Rutherford', category: 'Pinot Noir', year: 2014, price: 45, note: '', size: 750, location_id:22)
Wine.create(name: 'Dalton', vineyard: 'Dalton Winery', region: 'Galilee', category: 'Cabernet', year: 2013, price: 36, note: '', size: 750, location_id:23)
Wine.create(name: 'Bazelet', vineyard: 'Bazelet Winery', region: 'Golan', category: 'Cabernet', year: 2012, price: 37, note: '', size: 750, location_id:24)
Wine.create(name: 'Vinsanto', vineyard: 'Santo Winery', region: 'Santorini', category: 'Dessert', year: 2006, price: 22, note: '', size: 750, location_id:25)
